version: '3.6'
services:
  mongo:
    image: mongo
    ports: 
      - 27017:27017
  
  back:
    image: jcembrzynski/shopping-app:api
    ports:
      - 8080:8080
    depends_on: 
      - mongo

  front:
    image: jcembrzynski/shopping-app:app
    ports:
      - 4200:4200
    depends_on: 
      - back